<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-10-09 20:42
=======
# Generated by Django 4.2.5 on 2023-10-04 10:26
>>>>>>> a6ae25c84338e0b77f7b6d4de757176ecd0d7098

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Название товара', max_length=255, verbose_name='sku')),
                ('group', models.CharField(help_text='Группа товара', max_length=255, verbose_name='group')),
                ('category', models.CharField(help_text='Категория товара', max_length=255, verbose_name='category')),
                ('subcategory', models.CharField(help_text='Подкатегория товара', max_length=255, verbose_name='subcategory')),
                ('uom', models.IntegerField(help_text='Единица измерения товара', verbose_name='uom')),
            ],
        ),
    ]
