# Generated by Django 4.2.5 on 2023-10-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(help_text='Категория товара', max_length=255, verbose_name='category'),
        ),
    ]
