<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-10-09 20:42
=======
# Generated by Django 4.2.5 on 2023-10-04 17:01
>>>>>>> a6ae25c84338e0b77f7b6d4de757176ecd0d7098

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('store', models.CharField(help_text='Название магазина', max_length=255)),
                ('city', models.CharField(help_text='Город', max_length=255, verbose_name='city')),
                ('division', models.CharField(help_text='Дивизион', max_length=255, verbose_name='division')),
                ('type_format', models.IntegerField(help_text='Формат магазина', verbose_name='type_format')),
                ('loc', models.IntegerField(help_text='Локация магазина', verbose_name='loc')),
                ('size', models.IntegerField(help_text='Размер магазина', verbose_name='size')),
                ('is_active', models.IntegerField(help_text='флаг активного магазина на данный момент', verbose_name='is_active')),
            ],
        ),
    ]
