# Generated by Django 4.2.5 on 2023-09-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(help_text='Название магазина', max_length=255)),
                ('city', models.CharField(help_text='Город', max_length=255, verbose_name='city')),
                ('division', models.CharField(help_text='Дивизион', max_length=255, verbose_name='division')),
                ('type_format', models.IntegerField(help_text='Формат магазина', verbose_name='type_format')),
                ('loc', models.IntegerField(help_text='Локация магазина', verbose_name='loc')),
                ('size', models.IntegerField(help_text='Размер магазина', verbose_name='size')),
                ('is_active', models.IntegerField(help_text='флаг активного магазина на данный момент', verbose_name='is_active')),
            ],
        ),
    ]
