<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-10-09 20:59
=======
# Generated by Django 4.2.5 on 2023-10-07 16:43
>>>>>>> a6ae25c84338e0b77f7b6d4de757176ecd0d7098

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='id',
<<<<<<< HEAD
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
=======
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
>>>>>>> a6ae25c84338e0b77f7b6d4de757176ecd0d7098
        ),
    ]
