# Generated by Django 4.2.5 on 2023-10-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_categories_category'),
        ('shops', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_date', models.DateField(help_text='Дата будущих продаж')),
                ('units', models.IntegerField(help_text='Колличество позиций', verbose_name='units')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_units', models.ManyToManyField(help_text='Будущие продажи', related_name='sales_units', to='forecast.salesunits', verbose_name='будущие продажи')),
                ('sku', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='categories.categories', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='Дата отсечки')),
                ('forecast', models.ManyToManyField(help_text='Прогноз', related_name='forecast', to='forecast.forecastsales', verbose_name='прогноз')),
                ('store', models.ForeignKey(help_text='Выберите торговый центр', on_delete=django.db.models.deletion.CASCADE, to='shops.shops', verbose_name='торговый центр')),
            ],
        ),
    ]
