# Generated by Django 4.2.5 on 2023-09-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_date', models.DateField(help_text='Дата будущих продаж')),
                ('units', models.IntegerField(help_text='Единица', verbose_name='units')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='Дата отсечки')),
                ('forecast', models.ForeignKey(help_text='Прогноз', on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='forecast.forecastday', verbose_name='прогноз')),
                ('sku', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='categories.categories', verbose_name='товар')),
                ('store', models.ForeignKey(help_text='Выберите торговый центр', on_delete=django.db.models.deletion.CASCADE, to='shops.shops', verbose_name='торговый центр')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогноз',
                'ordering': ('store', 'sku', 'forecast'),
            },
        ),
    ]
