# Generated by Django 4.2.5 on 2023-09-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='sku',
        ),
        migrations.CreateModel(
            name='ForecastSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_units', models.ManyToManyField(help_text='Будущие продажи', related_name='sales_units', to='forecast.salesunits', verbose_name='будущие продажи')),
                ('sku', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='categories.categories', verbose_name='товар')),
            ],
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast',
            field=models.ManyToManyField(help_text='Прогноз', related_name='forecast', to='forecast.forecastsales', verbose_name='прогноз'),
        ),
    ]
