# Generated by Django 4.2.5 on 2023-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastday',
            name='units',
            field=models.IntegerField(help_text='Колличество позиций', verbose_name='units'),
        ),
    ]
