# Generated by Django 4.2.5 on 2023-09-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('categories', '0001_initial'),
        ('forecast', '0002_salesunits_alter_forecast_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='store',
        ),
        migrations.AddField(
            model_name='forecast',
            name='sku',
            field=models.ManyToManyField(help_text='Выберите товар', to='categories.categories', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='store',
            field=models.ManyToManyField(help_text='Выберите торговый центр', to='shops.shops', verbose_name='торговый центр'),
        ),
    ]
