# Generated by Django 4.2.5 on 2023-09-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажа'},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='fact',
        ),
        migrations.AddField(
            model_name='sales',
            name='fact',
            field=models.ManyToManyField(help_text='Фактическая продажа', to='sales.factsales', verbose_name='фактическая продажа'),
        ),
    ]
