# Generated by Django 4.2.5 on 2023-09-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_sales_rub_alter_sales_sales_run_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_units_promo',
            field=models.IntegerField(help_text='число проданных товаров с признаком промо', verbose_name='sales_units_promo'),
        ),
    ]
