# Generated by Django 4.2.5 on 2023-09-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('categories', '0001_initial'),
        ('sales', '0002_alter_sales_sales_rub_alter_sales_sales_run_promo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажа'},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
        migrations.AlterField(
            model_name='sales',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shops'),
        ),
    ]
