# Generated by Django 4.2.5 on 2023-09-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_options_remove_sales_fact_sales_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='fact',
            field=models.ManyToManyField(help_text='Фактическая продажа', related_name='fact', to='sales.factsales', verbose_name='фактическая продажа'),
        ),
    ]
